### PR TITLE
cleaned up html and js files removing console logs and white space.

### PR DESCRIPTION
**Pull request by wocaldwell**
cleaned up html and js files removing console logs and white space.

### CODE REVIEW

**Comment by BlaiseRoberts** [comment]
needs console.log when you delete from messageArray

**Comment by taylorperkins** [comment]
Add a console log that shows the array being updated as you remove cards

**Comment by taylorperkins** [comment]
yeah.. If you could hurry up.. That'd be great

**Comment by wocaldwell** [comment]
okay should be good now

**Comment by taylorperkins** [comment]
👍

**Pull request merged**
