### PR TITLE
added more teal accents

### PR DESCRIPTION
**Pull request by wocaldwell**
Changed the color of the blue background on the header and messages areas. Changed the checkbox font color. Added a teal bottom border to several elements including the buttons.

### CODE REVIEW

**Comment by taylorperkins** [comment]
killer:) Looks great man

**Comment by wocaldwell** [comment]
I added some more teal. Check the tooltip and modal buttons. .  .

**Comment by taylorperkins** [comment]
hell yeah!! Nice:D

**Comment by taylorperkins** [comment]
I dig it. Ive been trying to figure out a way to blend the background of the modal and the teal haha

**Comment by wocaldwell** [comment]
Yeah, I think that's a bit trickier. . .

**Comment by taylorperkins** [comment]
an easy way to spend 2 hours

**Comment by wocaldwell** [comment]
Okay, last bit of teal. . .

**Comment by taylorperkins** [comment]
sweet:)

**Comment by taylorperkins** [comment]
:+1:

**Comment by zakspence** [comment]
Looks great! :1st_place_medal:

**Comment by BlaiseRoberts** [comment]
👍

**Pull request merged**
