### PR TITLE
Adding some box-shadow to modal

### PR DESCRIPTION
**Pull request by taylorperkins**
added box-shadow to modal

### CODE REVIEW

**Comment by wocaldwell** [comment]
Oh, I see what you did there. . . cool teal backlighting effect on the modal!

**Comment by taylorperkins** [comment]
yeah!! It's still pretty crummy haha But I like that it's more than just the two plain colors

**Comment by zakspence** [comment]
lurve it

**Comment by BlaiseRoberts** [comment]
💯

**Pull request merged**
