### PR TITLE
Tp final delete button

### PR DESCRIPTION
**Pull request by taylorperkins**
woot. Changed the class from 'hidden' to 'hide'. Materialize thing.

### CODE REVIEW

**Comment by wocaldwell** [comment]
Hey Taylor, I checked out the `delete all button` and it works but there is a weird bug. If the first thing you do is make a new message, when you press `return` the `delete all button` disappears. Also, if you press the `delete all button` to clear the field THEN create two new messages, when you press `return` the second time the `delete all button` disappears.  It looks like the `hide` class is getting toggled on `return`.

**Comment by taylorperkins** [comment]
Good catch. Should be fixed

**Comment by zakspence** [comment]
1. Looks good
1. chyea

**Comment by wocaldwell** [comment]
Yes, looks good now! 👍

**Pull request merged**
